# General Settings
title: "WOILU PROJECT"
email: "joe@woilu.com"
email_2: "joe@mineversal.com"
description: >- # this means to ignore newlines until "baseurl:"
  WOILU (World Overview in Luminous Universe)

black_logo_1x: "/assets/images/logo.png"
black_logo_2x: "/assets/images/logo@2x.png"
light_logo_1x: "/assets/images/logo-light.png"
light_logo_2x: "/assets/images/logo-light@2x.png"

address_01: 'Moonshine St. <br>14/05 Light City,<br /> London, United Kingdom'
phone_number: "+62 851 5663 3114"
copyright_text: "© 2023 Woilu. All rights reserved."

google_analytics:
  enable: true
  key: "G-1B9DS3Z9XH"  # G-1B9DS3Z9XH

google_map: |
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d495.73968026468805!2d106.74866803458798!3d-6.274585484795009!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f0426a38adad%3A0x58e95a83d5c80c1!2s3%2C%20Jl.%20H.%20Toran%20No.65%2C%20RW.1%2C%20Rengas%2C%20Kec.%20Ciputat%20Tim.%2C%20Kota%20Tangerang%20Selatan%2C%20Banten%2015412!5e0!3m2!1sid!2sid!4v1637123939312!5m2!1sid!2sid" style="width:100%; height: 100%; border:0" allowfullscreen=""></iframe>

social_accounts:
  title: "Follow Us"
  links:
    - url: "https://www.twitter.com/Woilu_"
      icon: "jam jam-twitter"

    - url: "https://www.facebook.com/WoiluID"
      icon: "jam jam-facebook"

    - url: "https://www.instagram.com/Woilu"
      icon: "jam jam-instagram"

    - url: "#"
      icon: "jam jam-vimeo"
      
    - url: "https://www.youtube.com/mineversal"
      icon: "jam jam-youtube"


external_links:
  title: "Learn More"
  links:
    - url: "#"
      text: "About Us"
    - url: "#"
      text: "Our Story"
    - url: "#"
      text: "Projects"
    - url: "#"
      text: "Pricing"
    - url: "#"
      text: "Features"


external_links_02:
  title: "Need Help?"
  links:
    - url: "#"
      text: "Support"
    - url: "#"
      text: "Get Started"
    - url: "#"
      text: "Contact Us"
    - url: "#"
      text: "Terms of Use"
    - url: "#"
      text: "Privacy Policy"


external_links_03:
  title: "Company"
  links:
    - url: "#"
      text: "Our Team"
    - url: "#"
      text: "Strategy"
    - url: "#"
      text: "Service"
    - url: "#"
      text: "Mission"
    - url: "#"
      text: "Process"

footer_newsletter:
  title: "Our Newsletter"
  sub_title: "Subscribe to our newsletter to get our news & deals delivered to your inbox!"
  subscribe_button_text: "Join"


one_page_nav_settings:
  links:
    - text: "Home"
      url: "#home"
    - text: "Services"
      url: "#services"
    - text: "Experiences"
      url: "#experiences"
    - text: "Portfolio"
      url: "#portfolio"
    - text: "Testimonials"
      url: "#testimonials"
    - text: "Contact"
      url: "#contact"

author_page_header:
  header_background_image: "/assets/images/art/bg31.jpg"

gallery:
  images:
  - img: "/assets/images/art/z1.svg"
  - img: "/assets/images/art/z2.svg"
  - img: "/assets/images/art/z3.svg"
  - img: "/assets/images/art/z4.svg"
  - img: "/assets/images/art/z5.svg"
  - img: "/assets/images/art/z6.svg"
  - img: "/assets/images/art/z7.svg"
  - img: "/assets/images/art/z8.svg"